export const FETCH_POSTS='FETCH_POSTS';
export const ADD_POST='ADD_POST';
export const DELETE_POST='DELETE_POST';
export const ADD_USER_DETAILS='ADD_USER_DETAILS';
export const CHANGE_PASSWORD='CHANGE_PASSWORD';
